### ISSUE TITLE
Application crashes when trying to view new Invetory

### ISSUE THREAD

**Issue by TheHappyFella** [Leo-project-A/Inventory2.1#5]
When clicking on "View Inventory" to a brand new Inventory that I just have created, The application crashes with this error:

![image](https://user-images.githubusercontent.com/79667338/192855835-558ec272-c857-4809-861d-3027cbea304e.png)

The expected behavior is to get an empty Inventory.

FYI, when I started up the app again (after it crashed) and viewing the new Inventory, it fills the same inventory as "house_stock".

**Comment by Leo-project-A** [comment]
fixed the problem.
New empty inventory now works without crashing
